oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 5,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[2] = {
			['number'] = 36,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Sweden',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'F23',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['number'] = 36,
			['type'] = 'S-3B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VS-21',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 31,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[4] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = 'GA 5rd TS',
			['livery'] = '',
			['base'] = 'Senaki-Kolkhi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['number'] = 36,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'R/VF-101',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[6] = {
			['number'] = 3,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '317th Air Division',
			['livery'] = '',
			['base'] = 'Kobuleti',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[7] = {
			['number'] = 20,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'R/6th Cavalry',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[8] = {
			['number'] = 15,
			['type'] = 'B-52H',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'R/69 BS',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[9] = {
			['number'] = 12,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 10,
				['kills_ground'] = 1,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Laser Illumination'] = false,
				['CAP'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.3,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['CAP'] = 0.3,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 11,
				['damaged'] = 1,
				['ready'] = 4,
			},
			['name'] = 'VMFA-151',
			['livery'] = '',
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[10] = {
			['number'] = 36,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['name'] = '315th Air Division',
			['livery'] = '',
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[11] = {
			['number'] = 8,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 430,
				[2] = 450,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '177 ARW',
			['livery'] = '',
			['base'] = 'CVN-74 John C. Stennis',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[12] = {
			['number'] = 20,
			['type'] = 'UH-1H',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'R/17th Cavalry',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[13] = {
			['number'] = 9,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/171 ARW',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[14] = {
			['number'] = 3,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 3,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '171 ARW',
			['livery'] = '',
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[15] = {
			['number'] = 36,
			['type'] = 'MiG-19P',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/GA 4rd AS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 15,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[16] = {
			['number'] = 7,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[17] = {
			['number'] = 18,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 2,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['Laser Illumination'] = false,
				['CAP'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 1.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 18,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '54 TFS',
			['livery'] = '',
			['base'] = 'Kobuleti',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[18] = {
			['number'] = 36,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = 'R/VF-118/GA',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[19] = {
			['number'] = 12,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 4,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 0.7,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 26,
				['damaged'] = 2,
				['ready'] = 4,
			},
			['name'] = 'VMFA-157',
			['livery'] = '',
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[20] = {
			['number'] = 36,
			['type'] = 'S-3B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VS-22',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 29,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[21] = {
			['number'] = 36,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/58 TFS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[22] = {
			['number'] = 12,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 86,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['liveryModex'] = {
				[100] = 'vf-101 red',
				[105] = 'vf-101 grim reapers low vis',
				[111] = 'vf-101 dark',
			},
			['tasksCoef'] = {
				['Strike'] = 1.7,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1.5,
			},
			['player'] = true,
			['name'] = 'VF-101',
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
			['livery'] = {
				[1] = 'vf-101 grim reapers low vis',
				[2] = 'vf-101 dark',
			},
			['roster'] = {
				['lost'] = 44,
				['damaged'] = 1,
				['ready'] = 3,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 1,
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['ready'] = -1,
			},
		},
		[23] = {
			['number'] = 5,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[24] = {
			['number'] = 5,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VAW-125',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[25] = {
			['number'] = 4,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/GA 5rd TS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[26] = {
			['number'] = 12,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 1,
			},
			['country'] = 'Sweden',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 0.5,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1.5,
				['Anti-ship Strike'] = 2,
				['CAP'] = 1,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 26,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = 'F7',
			['livery'] = {
				[1] = '#4 Splinter F7 Skaraborgs Flygflottilj 76',
			},
			['base'] = 'Sukhumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[27] = {
			['number'] = 12,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 1,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Laser Illumination'] = false,
				['CAP'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['CAP'] = 1,
				['Intercept'] = 1.3,
			},
			['roster'] = {
				['lost'] = 12,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'VMFA-159',
			['livery'] = '',
			['base'] = 'Sukhumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[28] = {
			['number'] = 12,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 2,
			},
			['country'] = 'Sweden',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.7,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.5,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 29,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['name'] = 'F9',
			['livery'] = {
				[1] = '#4 Splinter F7 Skaraborgs Flygflottilj 76',
			},
			['base'] = 'Tbilissi-Lochini',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[29] = {
			['number'] = 8,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
				['Strike'] = true,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 17,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = 'GAH 2rd',
			['livery'] = '',
			['base'] = 'AMBROLAURI FARP LN41',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[30] = {
			['number'] = 3,
			['type'] = 'B-52H',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 2,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 12,
				['damaged'] = 4,
				['ready'] = 2,
			},
			['name'] = '69 BS',
			['livery'] = 'usaf standard',
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[31] = {
			['number'] = 5,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = 'VAW-125',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[32] = {
			['number'] = 8,
			['type'] = 'UH-1H',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 14,
				['damaged'] = 0,
				['ready'] = 14,
			},
			['name'] = '17th Cavalry',
			['livery'] = '',
			['base'] = 'KHASHURI FARP LM84',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[33] = {
			['number'] = 3,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '801 ARS',
			['livery'] = 'Standard USAF',
			['base'] = 'Senaki-Kolkhi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[34] = {
			['number'] = 3,
			['type'] = 'E-3A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '7 ACCS',
			['livery'] = 'usaf standard',
			['base'] = 'Kutaisi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[35] = {
			['number'] = 12,
			['type'] = 'S-3B',
			['score'] = {
				['kills_ship'] = 3,
				['kills_air'] = 0,
				['kills_ground'] = 1,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 14,
				['damaged'] = 1,
				['ready'] = 4,
			},
			['name'] = 'VS-22',
			['livery'] = '',
			['base'] = 'CVN-74 John C. Stennis',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[36] = {
			['number'] = 36,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 15,
			},
			['name'] = 'R/GA 7rd AS',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[37] = {
			['number'] = 12,
			['type'] = 'S-3B',
			['score'] = {
				['kills_ship'] = 8,
				['kills_air'] = 0,
				['kills_ground'] = 1,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 13,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = 'VS-21',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[38] = {
			['number'] = 36,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'R/54 TFS',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[39] = {
			['number'] = 7,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 7,
			},
			['name'] = 'R/315th Air Division',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[40] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['kills_ground'] = 4,
			},
			['country'] = 'Georgia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Anti-ship Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 0.5,
				['Fighter Sweep'] = 1.5,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 0.2,
				['Anti-ship Strike'] = 0.5,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 23,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = 'GA 7rd AS',
			['livery'] = '',
			['base'] = 'Senaki-Kolkhi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[41] = {
			['number'] = 36,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Sweden',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'F21',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[42] = {
			['number'] = 8,
			['type'] = 'AH-1W',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 20,
				['damaged'] = 1,
				['ready'] = 7,
			},
			['name'] = '6th Cavalry',
			['livery'] = '',
			['base'] = 'GORI FARP MM25',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[43] = {
			['number'] = 36,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Usa',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/VMFA-159',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[44] = {
			['number'] = 12,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['SEAD'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 24,
				['damaged'] = 2,
				['ready'] = 7,
			},
			['name'] = 'GA 3rd AS',
			['livery'] = 'af standard',
			['base'] = 'Vaziani',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[45] = {
			['number'] = 36,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Usa',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/VMFA-151',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 32,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[46] = {
			['number'] = 36,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Georgia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/GA 3rd AS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 15,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[47] = {
			['number'] = 12,
			['type'] = 'MiG-19P',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 4,
				['kills_ground'] = 2,
			},
			['country'] = 'Georgia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 26,
				['damaged'] = 0,
				['ready'] = 7,
			},
			['name'] = 'GA 4rd AS',
			['livery'] = '',
			['base'] = 'Vaziani',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[48] = {
			['number'] = 3,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'Tbilissi-Lochini',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[49] = {
			['number'] = 7,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/801 ARS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[50] = {
			['number'] = 7,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = 'R/317th Air Division',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[51] = {
			['number'] = 12,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 3,
				['kills_ground'] = 6,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Laser Illumination'] = false,
				['CAP'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1.5,
				['CAP'] = 0.5,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 27,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = '58 TFS',
			['livery'] = '',
			['base'] = 'Kutaisi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[52] = {
			['number'] = 20,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/VMFA-157',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[53] = {
			['number'] = 20,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = 'R/GAH 2rd',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[54] = {
			['number'] = 12,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 15,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'Random',
			['liveryModex'] = {
				[100] = 'vf-101 red',
				[105] = 'vf-101 grim reapers low vis',
				[111] = 'vf-101 dark',
			},
			['tasksCoef'] = {
				['Strike'] = 1.3,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 1.7,
			},
			['roster'] = {
				['lost'] = 17,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['name'] = 'VF-118/GA',
			['livery'] = {
				[1] = 'vf-101 grim reapers low vis',
				[2] = 'vf-101 dark',
			},
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
			['base'] = 'CVN-74 John C. Stennis',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
	},
	['red'] = {
		[1] = {
			['number'] = 12,
			['type'] = 'L-39A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = true,
				['Anti-ship Strike'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.5,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['CAP'] = 0.5,
				['Anti-ship Strike'] = 0.7,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 20,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '1./111AS.IAP',
			['livery'] = '',
			['base'] = 'Nalchik',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[2] = {
			['number'] = 2,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '23.OSAP',
			['livery'] = '',
			['base'] = 'Anapa-Vityazevo',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['number'] = 12,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 5,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Anti-ship Strike'] = 0.5,
				['SEAD'] = 1.5,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 25,
				['damaged'] = 2,
				['ready'] = 4,
			},
			['name'] = '1./135.IAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[4] = {
			['number'] = 12,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 8,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['SEAD'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 27,
				['damaged'] = 1,
				['ready'] = 6,
			},
			['name'] = '1./117.IAP',
			['livery'] = '',
			['base'] = 'Mozdok',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['number'] = 36,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./117.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 14,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[6] = {
			['number'] = 18,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Strike'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 0.3,
				['Fighter Sweep'] = 1.3,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 21,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = '1./153.IAP',
			['livery'] = '',
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[7] = {
			['number'] = 12,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 6,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.8,
				['Anti-ship Strike'] = 1,
				['SEAD'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 20,
				['damaged'] = 4,
				['ready'] = 6,
			},
			['name'] = '1./107.IAP',
			['livery'] = '',
			['base'] = 'Nalchik',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 1,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = -1,
			},
		},
		[8] = {
			['number'] = 24,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['inactive'] = true,
			['name'] = 'R/2nd GHR',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[9] = {
			['number'] = 12,
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['CAP'] = 1.5,
				['Fighter Sweep'] = 1,
				['Escort'] = 0.3,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 10,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '790.IAP',
			['livery'] = 'af standard',
			['base'] = 'Mozdok',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[10] = {
			['number'] = 36,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['name'] = 'R./19.IAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[11] = {
			['number'] = 4,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = 'R./29.OSAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[12] = {
			['number'] = 12,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['SEAD'] = 1.5,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 26,
				['damaged'] = 1,
				['ready'] = 5,
			},
			['name'] = '1./127.IAP',
			['livery'] = '',
			['base'] = 'Beslan',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[13] = {
			['number'] = 24,
			['type'] = 'Mi-8MT',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['inactive'] = true,
			['name'] = 'R/1st GHR',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 15,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[14] = {
			['number'] = 24,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['inactive'] = true,
			['name'] = 'R/13th GHR',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 20,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[15] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 21,
				['kills_ground'] = 1,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 0.3,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 12,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '1./113.IAP',
			['livery'] = '',
			['base'] = 'Mozdok',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[16] = {
			['number'] = 4,
			['type'] = 'A-50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '2457 SDRLO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Nalchik',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[17] = {
			['number'] = 8,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Anti-ship Strike'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 16,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = '1./61.IAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[18] = {
			['number'] = 36,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = 'R./37.IAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[19] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = '27.OSAP',
			['livery'] = '',
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[20] = {
			['number'] = 4,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/23.OSAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[21] = {
			['number'] = 5,
			['type'] = 'Su-24MR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Reconnaissance'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = 'O7 SDRLO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Krasnodar-Center',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[22] = {
			['number'] = 36,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./107.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[23] = {
			['number'] = 4,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '13th GHR',
			['livery'] = '',
			['base'] = 'LENIGORI FARP MN76',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[24] = {
			['number'] = 12,
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 10,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['CAP'] = 1.5,
				['Fighter Sweep'] = 1,
				['Escort'] = 0.5,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 12,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = '793.IAP',
			['livery'] = 'af standard',
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[25] = {
			['number'] = 4,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/25.OSAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[26] = {
			['number'] = 36,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./115.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 14,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[27] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 12,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['SEAD'] = false,
				['Anti-ship Strike'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 0.3,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['CAP'] = 1.5,
				['SEAD'] = 0.3,
				['Anti-ship Strike'] = 0.3,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 36,
				['damaged'] = 1,
				['ready'] = 9,
			},
			['name'] = '1./37.IAP',
			['livery'] = '',
			['base'] = 'Beslan',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[28] = {
			['number'] = 18,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 10,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = false,
				['SEAD'] = false,
				['Anti-ship Strike'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 0.3,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1,
				['SEAD'] = 0.3,
				['Anti-ship Strike'] = 0.3,
				['Intercept'] = 1.5,
			},
			['roster'] = {
				['lost'] = 33,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./19.IAP',
			['livery'] = '',
			['base'] = 'Nalchik',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[29] = {
			['number'] = 36,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 17,
			},
			['name'] = 'R./81.IAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[30] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 3,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
				['Laser Illumination'] = true,
			},
			['tasksCoef'] = {
				['Strike'] = 1.3,
				['Anti-ship Strike'] = 1,
				['SEAD'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 28,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '1./81.IAP',
			['sskill'] = 'Random',
			['livery'] = '',
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[31] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 17,
				['kills_ground'] = 1,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 0.5,
				['Fighter Sweep'] = 1.5,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['CAP'] = 1,
				['Intercept'] = 0.7,
			},
			['roster'] = {
				['lost'] = 21,
				['damaged'] = 0,
				['ready'] = 7,
			},
			['name'] = '1./123.IAP',
			['livery'] = '',
			['base'] = 'Beslan',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[32] = {
			['number'] = 2,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '1./29.OSAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[33] = {
			['number'] = 12,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 2,
				['kills_ground'] = 3,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Anti-ship Strike'] = 1,
				['SEAD'] = 1.5,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 31,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '1./115.IAP',
			['livery'] = '',
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[34] = {
			['number'] = 4,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/27.OSAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[35] = {
			['number'] = 36,
			['type'] = 'L-39A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R./115AS.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[36] = {
			['number'] = 12,
			['type'] = 'L-39A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = true,
				['Anti-ship Strike'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.5,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['CAP'] = 0.5,
				['Anti-ship Strike'] = 0.7,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 22,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '1./115AS.IAP',
			['livery'] = '',
			['base'] = 'Beslan',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[37] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = false,
				['Strike'] = false,
				['Escort'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = 'O/159.IAP',
			['livery'] = '',
			['base'] = 'Krasnodar-Center',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[38] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 4,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 0.5,
				['Fighter Sweep'] = 1.5,
				['Escort'] = 2,
				['CAP'] = 1.3,
				['Intercept'] = 0.5,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./133.IAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[39] = {
			['number'] = 6,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 6,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = '2.OSAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Sochi-Adler',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[40] = {
			['number'] = 5,
			['type'] = 'MiG-25RBT',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['AWACS'] = true,
				['Reconnaissance'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = '09 SDRLO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Krasnodar-Center',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[41] = {
			['number'] = 36,
			['type'] = 'L-39A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R./111AS.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 20,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[42] = {
			['number'] = 36,
			['type'] = 'MiG-27K',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./127.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[43] = {
			['number'] = 36,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./133.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[44] = {
			['number'] = 2,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '25.OSAP',
			['livery'] = '',
			['base'] = 'Krasnodar-Center',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[45] = {
			['number'] = 4,
			['type'] = 'A-50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '2457.I SDRLO',
			['livery'] = '',
			['base'] = 'Krasnodar-Center',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[46] = {
			['number'] = 4,
			['type'] = 'Il-76MD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '13.OSAP',
			['livery'] = '',
			['base'] = 'Nalchik',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[47] = {
			['number'] = 36,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./135.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 17,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[48] = {
			['number'] = 8,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = 'R./61.IAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[49] = {
			['number'] = 36,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./153.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[50] = {
			['number'] = 36,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./113.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[51] = {
			['number'] = 36,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R./123.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 20,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[52] = {
			['number'] = 4,
			['type'] = 'Mi-24V',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 28,
				['damaged'] = 0,
				['ready'] = 0,
			},
			['name'] = '2nd GHR',
			['livery'] = '',
			['base'] = 'TSKHINVALI FARP MM27',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[53] = {
			['number'] = 4,
			['type'] = 'Il-76MD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R./13.OSAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[54] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 5,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
				['Laser Illumination'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Anti-ship Strike'] = 1.7,
				['SEAD'] = 2,
				['Laser Illumination'] = 1,
			},
			['roster'] = {
				['lost'] = 9,
				['damaged'] = 3,
				['ready'] = 8,
			},
			['name'] = '1./41.IAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[55] = {
			['number'] = 36,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R./41.IAP',
			['inactive'] = true,
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[56] = {
			['number'] = 4,
			['type'] = 'Mi-8MT',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Transport'] = true,
			},
			['skill'] = 'High',
			['helicopter'] = true,
			['roster'] = {
				['lost'] = 6,
				['damaged'] = 0,
				['ready'] = 7,
			},
			['name'] = '1st GHR',
			['livery'] = '',
			['base'] = 'NOGIR FARP MN76',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[57] = {
			['number'] = 36,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = 'R/159.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 36,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[58] = {
			['number'] = 6,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 1,
				['ready'] = 0,
			},
			['name'] = '3.OSAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Beslan',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
	},
}
